### ISSUE TITLE
Vertically misaligned frames on some devices

### ISSUE THREAD

**Issue by SkariDamm** [getbouncer/cardscan-android#31] opened 2019-08-14 13:48 UTC
First of all, thanks for a great library! I've been working on implementing basic payment card scanning into a react native application with good success.

There is a minor layout issue on some devices. I noticed it on a Pixel 3XL but on a standard Pixel 1 it works fine. I'm assuming it might have something to do with the notch on the Pixel 3XL since it seems to be misaligned by the height of the notch.  

![Screenshot_20190814-132923](https://user-images.githubusercontent.com/2642407/63026137-27979f80-be9a-11e9-9016-0b07325fd120.png)

**Comment by kingst** [comment] 2019-08-14 15:19
Which version of the library are you on? I just tried it on my 3xl simulator and it seemed ok.

![image](https://user-images.githubusercontent.com/474745/63033307-40895c00-be6c-11e9-9754-dfb0679a74dc.png)

**Comment by kingst** [comment] 2019-08-14 15:22
Oh I think I can see a difference, it looks like you have a black strip at the top where as my version goes around the notch. This could be a build setting or library version issue. If you can help me reproduce it I'll fix it.

Can you post your project source code somewhere?

**Comment by SkariDamm** [comment] 2019-08-15 11:26
I'm not really in the position to share our complete source code, but I might be able to share certain bits if you tell me what it is you'd like to inspect.

If you'd like to try reproducing it on your end you should know we're developing a react native app that uses react navigation for navigation. This screen is the only one that has this black banner surrounding the notch. I'm running version 1.0.5001 of your library.

**Comment by kingst** [comment] 2019-08-15 13:47
We don't have any experience with react native, so if you could create a "hello world" app that uses react navigation to embed the cardscan activity and we can reproduce it, we'll be able to debug and fix this much quicker.

**Comment by kingst** [comment] 2019-09-02 10:55
Closing this issue. Please feel free to provide me with a simple example that helps reproduce the issue and I'll take a look.

**Comment by magedsoham** [comment] 2019-10-03 19:46
No we are developing a native android app

**Comment by kingst** [comment] 2019-10-03 19:50
Ok, good to know. I just got my Xiaomi 7 phone today so hopefully I can reproduce it soon and post a fix.

**Comment by Abdelrhman22** [comment] 2019-10-03 19:55
As maged mentioned , it is native android app .

**Comment by kingst** [comment] 2019-10-05 12:44
ok, fix on the way. Here is the PR https://github.com/getbouncer/cardscan-android/pull/38 and we'll push a new release out either this weekend or early next week

**Comment by kingst** [comment] 2019-10-06 19:12
Ok, I just shipped version `1.0.5102`, try it out and let me know if it fixed it.

**Comment by magedsoham** [comment] 2019-10-07 12:12
Perfect !! working fine now.

**Comment by kingst** [comment] 2019-10-07 12:30
Ok, closing this issue

**Closed by kingst** 2019-10-07 12:30 UTC
